### ISSUE TITLE
Not working with OpenEMU

### ISSUE THREAD

**Issue by wmollenkamp** [qibinc/JoyMapperSilicon#3]
I am able to use it while configuring my controller setup, but when trying to play the actual game it does not work. I think there is some disagreement between the two, but I'm not sure what.

**Comment by qibinc** [comment]
Hi @wmollenkamp ,

Thanks for your interest in this work. This software won't work if the original game/platform has controller support (e.g., Steam Controller support) set to **on** (even if they don't work yet) because they take away the control. Please **turn off** original controller support: 1. set to keyboard mode in the game/platform; 2. completely turn off controller support; 3. open JoyMapperSilicon and map the controller actions to keys).

**Comment by jrachele** [comment]
How do we go about completely turning off controller support in OpenEMU? If there isn't an option for it, is there any way to exclude controller support from MacOS itself on an app-by-app basis?
